### ISSUE TITLE
Do you have a discord?

### ISSUE THREAD

**Issue by iuhairways** [NVB9ALT/Bookmarklet-console#1]

**Comment by NVB9ALT** [comment]
I have tried several times, but no, I do not. Discord is blocked because I use a school computer, and when I try to make a Discord account on a proxy it needs me to confirm my identity by sending a text to my phone number...but I don't have a phone.

**Comment by iuhairways** [comment]
oh ok!

**Comment by iuhairways** [comment]
i do have a request though

**Comment by NVB9ALT** [comment]
wat is it

**Comment by iuhairways** [comment]
to make bookmarklet versions for my livery changer

**Comment by NVB9ALT** [comment]
I was planning, I think, on lumping the livery changer addon into the bookmarklet Realism Addon once I add all the liveries from Spice9's multiliveries addon. It's kind of embarrasing that I haven't worked on that, however (I have like 20-odd ideas to implement in the realism addon lol).

**Comment by githubuser589** [comment]
> I have tried several times, but no, I do not. Discord is blocked because I use a school computer, and when I try to make a Discord account on a proxy it needs me to confirm my identity by sending a text to my phone number...but I don't have a phone.

Have you tried using an SMS receiver, such as 5sim? It worked for me.

**Comment by NVB9ALT** [comment]
> 
> Have you tried using an SMS receiver, such as 5sim? It worked for me.

5sim costs money, do you know of any that are free?

**Comment by NVB9ALT** [comment]
Have a Discord now, "nvb9".
